<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />



<title>odds.n.ends vignette</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>
<script>// Hide empty <a> tag within highlighted CodeBlock for screen reader accessibility (see https://github.com/jgm/pandoc/issues/6352#issuecomment-626106786) -->
// v0.0.1
// Written by JooYoung Seo (jooyoung@psu.edu) and Atsushi Yasumoto on June 1st, 2020.

document.addEventListener('DOMContentLoaded', function() {
  const codeList = document.getElementsByClassName("sourceCode");
  for (var i = 0; i < codeList.length; i++) {
    var linkList = codeList[i].getElementsByTagName('a');
    for (var j = 0; j < linkList.length; j++) {
      if (linkList[j].innerHTML === "") {
        linkList[j].setAttribute('aria-hidden', 'true');
      }
    }
  }
});
</script>
<style type="text/css">
a.anchor-section {margin-left: 10px; visibility: hidden; color: inherit;}
a.anchor-section::before {content: '#';}
.hasAnchor:hover a.anchor-section {visibility: visible;}
</style>
<script>// Anchor sections v1.0 written by Atsushi Yasumoto on Oct 3rd, 2020.
document.addEventListener('DOMContentLoaded', function() {
  // Do nothing if AnchorJS is used
  if (typeof window.anchors === 'object' && anchors.hasOwnProperty('hasAnchorJSLink')) {
    return;
  }

  const h = document.querySelectorAll('h1, h2, h3, h4, h5, h6');

  // Do nothing if sections are already anchored
  if (Array.from(h).some(x => x.classList.contains('hasAnchor'))) {
    return null;
  }

  // Use section id when pandoc runs with --section-divs
  const section_id = function(x) {
    return ((x.classList.contains('section') || (x.tagName === 'SECTION'))
            ? x.id : '');
  };

  // Add anchors
  h.forEach(function(x) {
    const id = x.id || section_id(x.parentElement);
    if (id === '') {
      return null;
    }
    let anchor = document.createElement('a');
    anchor.href = '#' + id;
    anchor.classList = ['anchor-section'];
    x.classList.add('hasAnchor');
    x.appendChild(anchor);
  });
});
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>



<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">odds.n.ends vignette</h1>



<div id="creating-a-small-data-set-for-demonstration" class="section level2">
<h2>Creating a small data set for demonstration</h2>
<p><code>odds.n.ends</code> was created in order to take the results from a binary logistic regression model estimated using the <code>glm()</code> package and compute model significance, model fit, and the odds ratios and 95% confidence intervals typically reported from binary logistic regression analyses.</p>
<p>The small demonstration data set includes three variables. The first is a binary outcome variable (<code>sick</code>) with two values, 1 and 0 where 1 represents sick and 0 represents not sick. The second is an integer representing age in years (<code>age</code>) as one of the predictors, and a three-category nominal variable showing smoking status (<code>smoke</code>).</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># enter demo data</span></span>
<span id="cb1-2"><a href="#cb1-2"></a>sick &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>,</span>
<span id="cb1-3"><a href="#cb1-3"></a>          <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb1-4"><a href="#cb1-4"></a>age &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">23</span>, <span class="dv">25</span>, <span class="dv">26</span>, <span class="dv">34</span>, <span class="dv">54</span>, <span class="dv">46</span>, <span class="dv">48</span>, <span class="dv">95</span>, <span class="dv">81</span>, <span class="dv">42</span>, </span>
<span id="cb1-5"><a href="#cb1-5"></a>         <span class="dv">62</span>, <span class="dv">25</span>, <span class="dv">31</span>, <span class="dv">49</span>, <span class="dv">57</span>, <span class="dv">52</span>, <span class="dv">54</span>, <span class="dv">63</span>, <span class="dv">61</span>, <span class="dv">50</span>,</span>
<span id="cb1-6"><a href="#cb1-6"></a>         <span class="dv">43</span>, <span class="dv">35</span>, <span class="dv">26</span>, <span class="dv">74</span>, <span class="dv">34</span>, <span class="dv">46</span>, <span class="dv">43</span>, <span class="dv">65</span>, <span class="dv">81</span>, <span class="dv">42</span>, </span>
<span id="cb1-7"><a href="#cb1-7"></a>         <span class="dv">62</span>, <span class="dv">25</span>, <span class="dv">21</span>, <span class="dv">47</span>, <span class="dv">51</span>, <span class="dv">22</span>, <span class="dv">34</span>, <span class="dv">59</span>, <span class="dv">26</span>, <span class="dv">55</span>)</span>
<span id="cb1-8"><a href="#cb1-8"></a>smoke &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;Former&#39;</span>, <span class="st">&#39;Former&#39;</span>, <span class="st">&#39;Former&#39;</span>, <span class="st">&#39;Never&#39;</span>, <span class="st">&#39;Current&#39;</span>, <span class="st">&#39;Current&#39;</span>, <span class="st">&#39;Current&#39;</span>, <span class="st">&#39;Current&#39;</span>,</span>
<span id="cb1-9"><a href="#cb1-9"></a>           <span class="st">&#39;Never&#39;</span>, <span class="st">&#39;Former&#39;</span>, <span class="st">&#39;Never&#39;</span>, <span class="st">&#39;Former&#39;</span>, <span class="st">&#39;Current&#39;</span>, <span class="st">&#39;Former&#39;</span>, <span class="st">&#39;Never&#39;</span>, <span class="st">&#39;Current&#39;</span>,</span>
<span id="cb1-10"><a href="#cb1-10"></a>           <span class="st">&#39;Current&#39;</span>, <span class="st">&#39;Current&#39;</span>, <span class="st">&#39;Former&#39;</span>, <span class="st">&#39;Never&#39;</span>,<span class="st">&#39;Former&#39;</span>, <span class="st">&#39;Former&#39;</span>, <span class="st">&#39;Former&#39;</span>, <span class="st">&#39;Never&#39;</span>,</span>
<span id="cb1-11"><a href="#cb1-11"></a>           <span class="st">&#39;Current&#39;</span>, <span class="st">&#39;Current&#39;</span>, <span class="st">&#39;Current&#39;</span>, <span class="st">&#39;Current&#39;</span>, <span class="st">&#39;Never&#39;</span>, <span class="st">&#39;Former&#39;</span>, <span class="st">&#39;Never&#39;</span>, <span class="st">&#39;Former&#39;</span>,</span>
<span id="cb1-12"><a href="#cb1-12"></a>           <span class="st">&#39;Current&#39;</span>, <span class="st">&#39;Former&#39;</span>, <span class="st">&#39;Never&#39;</span>, <span class="st">&#39;Current&#39;</span>, <span class="st">&#39;Current&#39;</span>, <span class="st">&#39;Current&#39;</span>, <span class="st">&#39;Former&#39;</span>, <span class="st">&#39;Never&#39;</span>)</span>
<span id="cb1-13"><a href="#cb1-13"></a></span>
<span id="cb1-14"><a href="#cb1-14"></a><span class="co"># create data frame</span></span>
<span id="cb1-15"><a href="#cb1-15"></a>smokeData &lt;-<span class="st"> </span><span class="kw">data.frame</span>(sick, age, smoke)</span></code></pre></div>
<p>If your outcome variable is not coded as 1 and 0, you may want to check the variable level order before estimating your model so that you know which group will be modeled as the cases (the 1 values in the example data) and which group will be the reference group (the 0 values in our example data).</p>
</div>
<div id="estimating-the-model" class="section level2">
<h2>Estimating the model</h2>
<p>The <code>glm()</code> function will be used to estimate a binary logistic regression model predicting the <code>sick</code> outcome based on <code>age</code> and <code>smoke</code>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># estimate the logistic regression model object</span></span>
<span id="cb2-2"><a href="#cb2-2"></a>logisticModel &lt;-<span class="st"> </span><span class="kw">glm</span>(<span class="dt">formula =</span> sick <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>smoke, </span>
<span id="cb2-3"><a href="#cb2-3"></a>                     <span class="dt">data =</span> smokeData, </span>
<span id="cb2-4"><a href="#cb2-4"></a>                     <span class="dt">na.action =</span> na.exclude, </span>
<span id="cb2-5"><a href="#cb2-5"></a>                     <span class="dt">family =</span> <span class="kw">binomial</span>(logit))</span>
<span id="cb2-6"><a href="#cb2-6"></a></span>
<span id="cb2-7"><a href="#cb2-7"></a><span class="co"># print model summary for the logistic model object</span></span>
<span id="cb2-8"><a href="#cb2-8"></a><span class="kw">summary</span>(<span class="dt">object =</span> logisticModel)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = sick ~ age + smoke, family = binomial(logit), data = smokeData, 
##     na.action = na.exclude)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.0490  -0.6251   0.3009   0.6955   1.9315  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept) -3.28649    1.58753  -2.070   0.0384 * 
## age          0.10442    0.03711   2.814   0.0049 **
## smokeFormer -1.12544    0.94693  -1.189   0.2346   
## smokeNever  -2.47194    1.25103  -1.976   0.0482 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 54.548  on 39  degrees of freedom
## Residual deviance: 37.896  on 36  degrees of freedom
## AIC: 45.896
## 
## Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div id="using-odds.n.ends-to-get-significance-fit-or-and-ci" class="section level2">
<h2>Using odds.n.ends to get significance, fit, OR and CI</h2>
<p>The summary contains model coefficients, coefficient significance, and deviance and AIC which are measures of lack of fit of the model. While this information is useful in determining which of the predictors is significant and whether the deviance (lack of fit) was reduced between a null model with no predictors in it and an estimated model.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># open odds.n.ends package</span></span>
<span id="cb4-2"><a href="#cb4-2"></a><span class="kw">library</span>(<span class="dt">package =</span> <span class="st">&quot;odds.n.ends&quot;</span>)</span>
<span id="cb4-3"><a href="#cb4-3"></a></span>
<span id="cb4-4"><a href="#cb4-4"></a><span class="co"># get the  basics</span></span>
<span id="cb4-5"><a href="#cb4-5"></a><span class="kw">odds.n.ends</span>(<span class="dt">mod =</span> logisticModel)</span></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>## $`Logistic regression model significance`
## Chi-squared        d.f.           p 
##      16.652       3.000       0.001 
## 
## $`Contingency tables (model fit): frequency predicted`
##                 Number observed
## Number predicted  1  0 Sum
##              1   19  4  23
##              0    4 13  17
##              Sum 23 17  40
## 
## $`Count R-squared (model fit): percent correctly predicted`
## [1] 80
## 
## $`Model sensitivity`
## [1] 0.826087
## 
## $`Model specificity`
## [1] 0.7647059
## 
## $`Predictor odds ratios and 95% CI`
##                     OR       2.5 %    97.5 %
## (Intercept) 0.03738466 0.001102466 0.6610966
## age         1.11006273 1.041062741 1.2081565
## smokeFormer 0.32450861 0.045942281 2.0537937
## smokeNever  0.08442065 0.005379054 0.8158007</code></pre>
<p>The results show that the model was statistically significantly better than a baseline model at explaining the outcome [<span class="math inline">\(\chi^2\)</span>(3) = 16.652; p = .001]. The model correctly predicted 19 of those who were sick (<code>sick = 1</code>) and 13 of those who were not sick (<code>sick = 0</code>), for a total of 32 correctly predicted out of 40 (Count-<span class="math inline">\(R^2\)</span> = .80 or 80% correctly predicted). The model was more sensitive, with 82.6% of those who were sick (the cases) correctly predicted, and less specific, with 76.5% of the members of the reference group correctly predicted. Age was a statistically significant predictor of the outcome; for every one year increase in age, the odds of being sick increased by 11% (OR = 1.11; 95% CI: 1.04 - 1.21). There was no statistically significant difference in odds of being sick for former smokers compared to current smokers. Never smokers had 92% lower odds of being sick compared to current smokers; this decrease was statistically significant (OR = .08; 95% CI: .005 - .82).</p>
<p>The <code>odds.n.ends</code> package has several additional options including the ability to get an ROC curve (use option <code>rocPlot = TRUE</code>) and histograms of predicted probabilities (use option <code>predProbPlot = TRUE</code>). Colors for these plots can be set with options <code>color1 =</code> and <code>color2 =</code>. Finally, the threshold for a predicted probability being counted as a case (outcome = 1) has a default value of .5, so any predicted probability that is .5 or higher will be counted as a case, and any predicted probability below .5 will be counted as a reference group member (outcome = 0). This threshold can be adjusted using the <code>thresh =</code> argument.</p>
<p>Example with other arguments specified:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="co"># add graphs, change threshold, specify color</span></span>
<span id="cb7-2"><a href="#cb7-2"></a><span class="kw">odds.n.ends</span>(<span class="dt">mod =</span> logisticModel,</span>
<span id="cb7-3"><a href="#cb7-3"></a>            <span class="dt">rocPlot =</span> <span class="ot">TRUE</span>,</span>
<span id="cb7-4"><a href="#cb7-4"></a>            <span class="dt">predProbPlot =</span> <span class="ot">TRUE</span>,</span>
<span id="cb7-5"><a href="#cb7-5"></a>            <span class="dt">thresh =</span> <span class="fl">.4</span>,</span>
<span id="cb7-6"><a href="#cb7-6"></a>            <span class="dt">color1 =</span> <span class="st">&#39;orange&#39;</span>,</span>
<span id="cb7-7"><a href="#cb7-7"></a>            <span class="dt">color2 =</span> <span class="st">&#39;blue&#39;</span>)</span></code></pre></div>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
